### ISSUE TITLE
Why set comments:true not working?

### ISSUE THREAD

**Issue by underweather** [vuejs/vue-ssr-docs#165]
I'm Using vue-ssr version^2.5.9 and set comments:true at Root vue (App.vue),but it seems not work.Has anybody ever met such problem? Has any suggestions? thank you very much~

**Comment by LinusBorg** [comment]
Hello @underweather 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
