### ISSUE TITLE
how to access store instance in external file with new factory pattern

### ISSUE THREAD

**Issue by woshoushuye** [vuejs/vue-ssr-docs#190]
hey guys, i need some help.
Trying to do ` import store from './vuex/index'` something like that in a external file, so that i can do store.commit any where i want.
but with the new pattern, store/router are created by a factory function. which make the import store not work.
anyone can offer some help would be appreciate, thx!!

**Comment by woshoushuye** [comment]
any other way to deal with this kind of problem is also helpful

**Comment by LinusBorg** [comment]
Hello @woshoushuye 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
