### ISSUE TITLE
Get data on server side

### ISSUE THREAD

**Issue by borodadada** [vuejs/vue-ssr-docs#258]
Hello, before render page i need get data from other server, i want get data on server side. After with data create page.
I try use

```
async beforeRouteEnter (to, from, next) {
        if( isServer ){  //variable true in entry-server.js 
           ......................  get data
        }
        next()
},

```
then i open page, data exist, after full load page disappears
How i can this do?

**Comment by LinusBorg** [comment]
Hello @borodadada 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
